const Hyderabad = [
  {
    _id: 1,
    Date: "2021-12-31",
    LocalName: "New Year's Day",
    Name: "New Year's Day",
    CountryCode: "US",
    Fixed: false,
    Global: true,
    LaunchYear: null,
    Type: "Public",
    Counties: "",
  },
  {
    _id: 2,
    Date: "2022-01-17",
    LocalName: "Martin Luther King, Jr. Day",
    Name: "Hyderabad. Day",
    CountryCode: "US",
    Fixed: false,
    Global: true,
    LaunchYear: null,
    Type: "Public",
    Counties: "",
  },
  {
    _id: 3,
    Date: "2022-02-21",
    LocalName: "Presidents Day",
    Name: "Washington's Birthday",
    CountryCode: "US",
    Fixed: false,
    Global: true,
    LaunchYear: null,
    Type: "Public",
    Counties: "",
  },
  {
    _id: 4,
    Date: "2022-04-15",
    LocalName: "Good Friday",
    Name: "Good Friday",
    CountryCode: "US",
    Fixed: false,
    Global: false,
    LaunchYear: null,
    Type: "Public",
    Counties: "US-CT,US-DE,US-HI,US-IN,US-KY,US-LA,US-NC,US-ND,US-NJ,US-TN",
  },
  {
    _id: 5,
    Date: "2022-04-15",
    LocalName: "Good Friday",
    Name: "Good Friday",
    CountryCode: "US",
    Fixed: false,
    Global: false,
    LaunchYear: null,
    Type: "Optional",
    Counties: "US-TX",
  },
  {
    _id: 6,
    Date: "2022-05-30",
    LocalName: "Memorial Day",
    Name: "Memorial Day",
    CountryCode: "US",
    Fixed: false,
    Global: true,
    LaunchYear: null,
    Type: "Public",
    Counties: "",
  },
  {
    _id: 7,
    Date: "2022-06-20",
    LocalName: "Juneteenth",
    Name: "Juneteenth",
    CountryCode: "US",
    Fixed: false,
    Global: true,
    LaunchYear: 2021,
    Type: "Public",
    Counties: "",
  },
  {
    _id: 8,
    Date: "2022-07-04",
    LocalName: "Independence Day",
    Name: "Independence Day",
    CountryCode: "US",
    Fixed: false,
    Global: true,
    LaunchYear: null,
    Type: "Public",
    Counties: "",
  },
  {
    _id: 9,
    Date: "2022-09-05",
    LocalName: "Labor Day",
    Name: "Labour Day",
    CountryCode: "US",
    Fixed: false,
    Global: true,
    LaunchYear: null,
    Type: "Public",
    Counties: "",
  },
  {
    _id: 10,
    Date: "2022-10-10",
    LocalName: "Columbus Day",
    Name: "Columbus Day",
    CountryCode: "US",
    Fixed: false,
    Global: false,
    LaunchYear: null,
    Type: "Public",
    Counties:
      "US-AL,US-AZ,US-CO,US-CT,US-DC,US-GA,US-ID,US-IL,US-IN,US-IA,US-KS,US-KY,US-LA,US-ME,US-MD,US-MA,US-MS,US-MO,US-MT,US-NE,US-NH,US-NJ,US-NM,US-NY,US-NC,US-OH,US-OK,US-PA,US-RI,US-SC,US-TN,US-UT,US-VA,US-WV",
  },
  {
    _id: 11,
    Date: "2022-11-11",
    LocalName: "Veterans Day",
    Name: "Veterans Day",
    CountryCode: "US",
    Fixed: false,
    Global: true,
    LaunchYear: null,
    Type: "Public",
    Counties: "",
  },
  {
    _id: 12,
    Date: "2022-11-24",
    LocalName: "Thanksgiving Day",
    Name: "Thanksgiving Day",
    CountryCode: "US",
    Fixed: false,
    Global: true,
    LaunchYear: 1863,
    Type: "Public",
    Counties: "",
  },
  {
    _id: 13,
    Date: "2022-12-26",
    LocalName: "Christmas Day",
    Name: "Christmas Day",
    CountryCode: "US",
    Fixed: false,
    Global: true,
    LaunchYear: null,
    Type: "Public",
    Counties: "",
  },
];

export default Hyderabad;
